POST http://localhost:7318/binV4/PurchaseItems/Create/SendMail
Content-Type: application/json

{"FK":"","sno":"","Date":"","Qty":0,"UnitRate":"","Amount":"","ItemName":"","PercentageValueAddition":"","MRP":""}