POST http://localhost:7318/binV4/pos/Bulk
Content-Type: application/json

{"BillNumber2425":0,"Date":"","CustomerName":"","ContactNumber":"","CustomerNumber":"","PaymentMode":"","GSTNumber":"","DateTime":""}