POST http://localhost:7318/binV4/SRVoucher/Bulk/MultiInsertWithCheck
Content-Type: application/json

[{"pk":"","Date":"","CustomerName":"","Description":""},{"pk":"","Date":"","CustomerName":"","Description":""}]