POST http://localhost:7318/binV4/BillsQrCode/Bulk/MultiInsertWithCheck
Content-Type: application/json

[{"ProductName":"","UnitRate":0,"sno":0,"DisPercentage":0,"DisRate":0,"GrossAmout":0,"Barcode":"","BillPk":"","pk":0},{"ProductName":"","UnitRate":0,"sno":0,"DisPercentage":0,"DisRate":0,"GrossAmout":0,"Barcode":"","BillPk":"","pk":0}]