POST http://localhost:7318/binV4/Generate/Create
Content-Type: application/json

{"ProductName":"","CostPrice":0,"ProductAliasName":"","SalePrice":0,"PercentageValueAddition":0,"UserDescription":"","InventorySerial":"","PurchasePk":"","SupplierName":"","BillNumber":""}