POST http://localhost:7318/binV4/Vouchers/Bulk/MultiInsertWithCheck
Content-Type: application/json

[{"BillNumber":"","Date":"","SupplierName":"","AliasName":"","TotalAmount":""},{"BillNumber":"","Date":"","SupplierName":"","AliasName":"","TotalAmount":""}]