POST http://localhost:7318/binV4/SalesReturns/Create/SendMail
Content-Type: application/json

{"ProductName":"","CostPrice":0,"ProductAliasName":"","SalePrice":0,"PercentageValueAddition":0,"UserDescription":"","SRRef":"","QrCode":""}