POST http://localhost:7318/binV4/Suppliers/Bulk/MultiInsertWithCheck
Content-Type: application/json

[{"SupplierName":"","AliasName":"","City":"","GST":"","Phone":0},{"SupplierName":"","AliasName":"","City":"","GST":"","Phone":0}]